name = "Piercer"
license = "MIT"
licenselink = "https://github.com/danielkvist/hugo-piercer-theme/blob/master/LICENSE"
description = ""
homepage = "https://github.com/danielkvist/hugo-piercer-theme"
tags = []
features = []
min_version = "0.41"

[author]
  name = "Danielkvist (Daniel Zaragoza)"
  homepage = "https://dkvist.com"
